name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build 

      - name: Bar
        working-directory: apps/bar
        run: zig build 

      - name: Font Viewer
        working-directory: apps/fontviewer
        run: zig build 

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
